version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build

  deploy:
    docker:
      - image: circleci/python:3.7.7
    steps:
        - run: pip3 install ansible boto boto3
        - run: echo ${SSH_KEY_FILE_CONTENT} > presentation.pem
        - run: ansible-playbook ec2-deploy.yml --user=ubuntu --key-file=presentation.pem

workflows:
  version: 2.1
  build:
    jobs:
      - build_and_test
      - deploy:
         requires:
          - build_and_test
         filters:
           branches:
              only: master
